import base64
import hashlib
import hmac
import os
import secrets
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlparse, urlunparse

import pandas as pd


class PostgresConnection:
    def __init__(self, url: str, psycopg_module: Any):
        self.url = url
        self.psycopg_module = psycopg_module
        self.conn = None

    def __enter__(self):
        if self.psycopg_module is None:
            raise RuntimeError("DATABASE_URL 已配置，但缺少 psycopg 依赖；请先安装 requirements.txt。")
        self.conn = self.psycopg_module.connect(self.url)
        return self

    def __exit__(self, exc_type, exc, traceback):
        if self.conn is None:
            return
        if exc_type is None:
            self.conn.commit()
        else:
            self.conn.rollback()
        self.conn.close()

    def execute(self, sql: str, params: tuple[Any, ...] = ()):
        if self.conn is None:
            raise RuntimeError("数据库连接尚未打开。")
        return self.conn.execute(db_sql(sql, use_postgres=True), params)


def db_sql(sql: str, *, use_postgres: bool) -> str:
    return sql.replace("?", "%s") if use_postgres else sql


def db_connect(
    *,
    use_postgres: bool,
    database_url: str,
    db_path: Path,
    psycopg_module: Any,
):
    if use_postgres:
        return PostgresConnection(database_url, psycopg_module)
    return sqlite3.connect(db_path)


def db_read_sql_query(
    sql: str,
    conn: Any,
    *,
    params: tuple[Any, ...] = (),
    use_postgres: bool,
) -> pd.DataFrame:
    if use_postgres and isinstance(conn, PostgresConnection):
        cursor = conn.execute(sql, params)
        columns = [getattr(column, "name", column[0]) for column in cursor.description or []]
        return pd.DataFrame(cursor.fetchall(), columns=columns)
    raw_conn = conn.conn if hasattr(conn, "conn") and getattr(conn, "conn", None) is not None else conn
    return pd.read_sql_query(db_sql(sql, use_postgres=use_postgres), raw_conn, params=params)


def db_columns(conn: Any, table: str, *, use_postgres: bool) -> set[str]:
    if use_postgres:
        rows = conn.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = ?
            """,
            (table,),
        ).fetchall()
        return {str(row[0]) for row in rows}
    return {row[1] for row in conn.execute(f"PRAGMA table_info({table})").fetchall()}


def db_integrity_errors(psycopg_module: Any) -> tuple[type[BaseException], ...]:
    errors: list[type[BaseException]] = [sqlite3.IntegrityError]
    if psycopg_module is not None:
        errors.append(psycopg_module.IntegrityError)
    return tuple(errors)


def db_autoincrement_pk(*, use_postgres: bool) -> str:
    return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if use_postgres else "INTEGER PRIMARY KEY AUTOINCREMENT"


def db_insert_and_get_id(
    conn: Any,
    table: str,
    values: dict[str, Any],
    *,
    use_postgres: bool,
) -> int:
    columns = list(values.keys())
    placeholders = ", ".join(["?"] * len(columns))
    column_sql = ", ".join(columns)
    sql = f"INSERT INTO {table} ({column_sql}) VALUES ({placeholders})"
    params = tuple(values[column] for column in columns)
    if use_postgres:
        return int(conn.execute(f"{sql} RETURNING id", params).fetchone()[0])
    cursor = conn.execute(sql, params)
    return int(cursor.lastrowid)


def password_hash(password: str, *, iterations: int, salt: bytes | None = None) -> str:
    salt = salt or secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations)
    return "pbkdf2_sha256${}${}${}".format(
        iterations,
        base64.b64encode(salt).decode("ascii"),
        base64.b64encode(digest).decode("ascii"),
    )


def verify_password(password: str, stored_hash: str) -> bool:
    try:
        algorithm, iterations, salt_b64, digest_b64 = stored_hash.split("$", 3)
        if algorithm != "pbkdf2_sha256":
            return False
        salt = base64.b64decode(salt_b64.encode("ascii"))
        expected = base64.b64decode(digest_b64.encode("ascii"))
        actual = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, int(iterations))
        return hmac.compare_digest(actual, expected)
    except Exception:
        return False


def capture_upload_public_url(
    *,
    upload_api_public_url: str,
    upload_api_port: int,
    upload_api_path: str,
    current_context_url: str = "",
) -> str:
    same_origin_upload = os.getenv("CAPTURE_UPLOAD_SAME_ORIGIN", "").strip().lower() in {"1", "true", "yes", "on"}
    app_public_url = os.getenv("APP_PUBLIC_URL", "").strip()
    if same_origin_upload:
        for candidate in [app_public_url, current_context_url.strip()]:
            if not candidate:
                continue
            parsed = urlparse(candidate)
            if parsed.scheme and parsed.netloc:
                return urlunparse((parsed.scheme, parsed.netloc, upload_api_path, "", "", ""))

    if upload_api_public_url:
        return upload_api_public_url

    for candidate in [app_public_url, current_context_url.strip()]:
        if not candidate:
            continue
        parsed = urlparse(candidate)
        if parsed.scheme and parsed.hostname:
            default_port = 443 if parsed.scheme == "https" else 80
            resolved_port = int(upload_api_port)
            netloc = parsed.hostname if resolved_port == default_port else f"{parsed.hostname}:{resolved_port}"
            return urlunparse((parsed.scheme, netloc, upload_api_path, "", "", ""))
    return f"http://127.0.0.1:{upload_api_port}{upload_api_path}"


def load_user_setting_value(conn: Any, user_id: int, key: str) -> str:
    row = conn.execute("SELECT value FROM app_settings WHERE user_id = ? AND key = ?", (int(user_id), key)).fetchone()
    return str(row[0]) if row and row[0] is not None else ""


def save_user_setting_value(conn: Any, user_id: int, key: str, value: str) -> None:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    existing = conn.execute("SELECT 1 FROM app_settings WHERE user_id = ? AND key = ?", (int(user_id), key)).fetchone()
    if existing:
        conn.execute(
            "UPDATE app_settings SET value = ?, updated_at = ? WHERE user_id = ? AND key = ?",
            (value.strip(), now, int(user_id), key),
        )
    else:
        conn.execute(
            "INSERT INTO app_settings (user_id, key, value, updated_at) VALUES (?, ?, ?, ?)",
            (int(user_id), key, value.strip(), now),
        )


def get_or_create_capture_upload_token(
    user_id: int,
    *,
    init_db: Any,
    db_connect: Any,
    load_user_setting_value_fn: Any,
    save_user_setting_value_fn: Any,
) -> str:
    init_db()
    with db_connect() as conn:
        token = load_user_setting_value_fn(conn, int(user_id), "capture_upload_token")
        if token:
            return token
        token = secrets.token_urlsafe(24)
        save_user_setting_value_fn(conn, int(user_id), "capture_upload_token", token)
        return token
